spring:
  application:
    name: geozip
  datasource:
    url: jdbc:postgresql://localhost:5432/santanderDB
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

wiremock:
  url: http://localhost:8081

spring.classformat.ignore: true


#curl -X GET "http://localhost:8080/api/cep?cep=04831031"